# taps
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "adoptopenjdk/openjdk"
tap "pharo-project/pharo"

# utilities
brew "antigen"
brew "bash"
brew "bat"
brew "beancount"
brew "chruby"
brew "cloc"
brew "diff-so-fancy"
brew "direnv"
brew "exa"
brew "fd"
brew "fzf"
brew "gdu"
brew "git-delta"
brew "gitui"
brew "gnuplot"
brew "gron"
brew "hexyl"
brew "hstr"
brew "htop"
brew "icdiff"
brew "imagemagick"
brew "libfaketime"
brew "lsd"
brew "jq"
brew "neovim"
brew "pass"
brew "procs"
brew "q"
brew "ripgrep"
brew "ruby-install"
brew "scrcpy"
brew "starship"
brew "stgit"
brew "stow"
brew "textql"
brew "tig"
brew "tree"
brew "truncate"
brew "watch"
brew "wget"

# GnuPG and GPGTools/pinentry-mac
brew "gnupg"
brew "pinentry-mac"

# Java
brew "openjdk"
brew "maven"
brew "ant"
brew "gradle"
brew "jenv"
cask "java6"
cask "adoptopenjdk/openjdk/adoptopenjdk8"
cask "adoptopenjdk/openjdk/adoptopenjdk11"
cask "eclipse-java"
cask "jd-gui"

# casks
cask "audacity"
cask "authy"
cask "caffeine"
cask "deezer"
cask "deskreen"
cask "docker"
cask "google-chrome"
cask "google-drive"
cask "iterm2"
cask "keepassx"
cask "keybase"
cask "ngrok"
cask "pharo-launcher"
cask "spotify"
cask "telegram"
cask "the-unarchiver"
cask "vagrant"
cask "virtualbox"
cask "virtualbox-extension-pack"
cask "visual-studio-code"
cask "whatsapp"

if MacOS.version == :mojave
  cask "horndis"
end

# android
cask "android-file-transfer"
cask "android-platform-tools"

# fonts
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
