[line_break]
disabled = true

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

[git_branch]
symbol = " "

[package]
disabled = true

[java]
symbol = "java:"
style = "bold yellow"
format = "[$symbol\\(](bold blue)[${version}]($style)[\\)](bold blue)"

[nodejs]
symbol = "node:"
style = "bold yellow"
format = "[$symbol\\(](bold blue)[${version}]($style)[\\)](bold blue)"
