#!/bin/bash

if [[ $OSTYPE == 'darwin'* ]]; then
    open -a Docker
    while (! docker stats --no-stream &> /dev/null); do
        printf "."
        sleep 1
    done
    printf "\nDocker initialized\n"
fi

docker ps -aq | xargs docker stop
docker ps -aq | xargs docker rm
docker images -q | xargs docker rmi
docker volume ls -q | xargs docker volume rm
docker volume prune -f
docker network prune -f
docker system prune -f


if [[ $OSTYPE == 'darwin'* ]]; then
    osascript -e 'quit app "Docker"'
fi

rm -rf .docker

